apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: trading

resources:
  - namespace.yaml
  - pvc.yaml
  - configmap.yaml
  - schwab-server-deployment.yaml
  - trading-agent-deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: trading-agent
  app.kubernetes.io/part-of: trading-system
