apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trading-journal-pvc
  namespace: trading
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi
